Make startForeground actually start the foreground
Most miserable thing to figure out.
- Increased minimum SDK to 34 (does things at those levels; means this only runs on Android 14)
- Adjusted things in manifest (possible reason why this didn't work beforehand was that some value there was incorrect leading to a NoSuchMethodError)
- Requests for correct permissions (dangerous permissions were not requested beforehand) and checks permissions before doing things that require them (activity and notifications)
- Creates a notification channel for the foreground notification (is needed otherwise the notifications won't work)
- Separated binding from StartStepCounter (not sure if it's necessary; my thinking is that if the service isn't launched in time then the binding needs to be set later)
- Added resolution strategy (another thing that may have solved what the first point's issue mentions)